%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/ruihong/Documents/MATLAB/alldata.xlsx
%    Worksheet: scoresheet
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/05/17 18:33:16

%% Import the data
[~, ~, raw] = xlsread('/Users/ruihong/Documents/MATLAB/alldatanew.xlsx','scoresheet');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names

gray1 = data(:,1);
circu = data(:,2);
is = data(:,3);

%% Clear temporary variables
clearvars data raw;

x=gray1.';
y=is.';
c=circu.';

z = [x;y];
zz = [c;y];
%subplot(2,1,1)
for i = 1:1:size(x,2)
    if y(i) == 1
       plot(x(i),c(i),  '+r');
    else
       plot(x(i),c(i),  'o');
    end
    hold on
end

 axis([0,255,0,1.5]);
 %??????????
num = 3;   %????
wSample = 1/size(x,2)*ones(size(x,2), 1);%?????
wClass = zeros(num,1);%?????
h0 = zeros(num,1);
h1 = zeros(num,1);
h2 = zeros(num,1);%?????
h3 = zeros(num,1);%?????
be = ones(num,1);%???????????????

for i1 = 1:1:num
    for gb=0:1:255
        for gt=0:1:255
            for cb=0:0.1:1.5
              for ct=0:0.1:1.5
   
 e0 = 0;  %?????
 e1 = 0;  %?????
    for k = 1:478   %?????????????????????
     if ct<zz(1,k)||zz(1,k)<cb||gt<z(1,k)||z(1,k)<gb
         if z(2,k) == 1
             e0 = e0+wSample(k);
         else
             e1 = e1+wSample(k);
         end
     else
         if z(2,k) == -1
             e0 = e0+wSample(k);
         else
             e1 = e1+wSample(k);
         end
     end
    end 
   

     if be(i1) > e0
       be(i1) = e0;  
       h0(i1)=gb;
       h1(i1)=gt;
       h2(i1) = cb;
        h3(i1)=ct;    
         end
     end
     end
     end
     end
     
     
 
%?????????
 line([h0(i1) h0(i1)],[0 1.5],'color','c','LineWidth',4)
 line([h1(i1) h1(i1)],[0 1.5],'color','c','LineWidth',4)%[][][x? x?]][y? y?]?[]??????????
  line([0 255],[h2(i1) h2(i1)],'color','c','LineWidth',4) %[][][x? x?]][y? y?]?[]??????????
    line([0 255],[h3(i1) h3(i1)],'color','c','LineWidth',4) %[][][x? x?]][y? y?]?[]??????????


 sumclass = sum(wSample(:,1));%????????????
  %??????????????????????
  we = be(i1)/sumclass;
 wClass(i1) = 0.5*log((1-we)/we);
 %?????????
   for k1 = 1:478   
     if zz(1,k1) > h3(i1)||zz(1,k1)<h2(i1)||h1(i1)<z(1,k)||z(1,k)<h0(i1)
         if z(2,k1) == 1
             wSample(k1) = exp(wClass(i1))*wSample(k1);
         else
             wSample(k1) = exp(-wClass(i1))*wSample(k1);
         end
     else
         if z(2,k1) == -1
            wSample(k1) = exp(wClass(i1))*wSample(k1);
         else
            wSample(k1) = exp(-wClass(i1))*wSample(k1);
         end
     end
   end 
   
   
end
hold off
%?????????
%subplot(2,1,2)
G=zeros(4781,1);
abak = 0:0.1:478;
for q=1:1:4781
  
    for abai = 1:num
        if abak(q) > h(abai)
            G(q) = G(q) + wClass(abai)*(-1);
        else
             G(q) = G(q) + wClass(abai)*(1);
        end  
    end
      
end
%plot(abak,G,'r','LineWidth',4) 
 hold on
 SG=zeros(4781,1);%??sign????
 for i = 1:1:4781
   SG(i) = sign(G(i));  
 end
%plot(abak,SG,'Color',[0 1 0],'LineWidth',4)